apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:YfIacd7PzU8BQWC71DoxC3HwInXgxrDuexMMM6pY0E8XKiHTIjRJi698vkA2MENwTln3PFu4Jl3I1+RSD/xmZMnAsmqQGh3J/QcsHGScsSan1K3GbwX4KpL7yS1F1D7YfP1FKvswPo5zLhAvGVqU1RuR+cjcQgaMVBCx6Kd52fMq2MAL3VzEkSP8n19LgsnxiMScYx7x5nEESCw0lapDUbZzDv5EqdQT/WBN+BqRTjbmyRtr95YlROZYLGhe4f6RBd8EpHCavhSJa28TqlU9hOvaJAocJRVYlShJN+zKKQgrm30dbTv93knYTww=,iv:GYe/Tc33qv1ZbplkKSzTENlvGo1HQhPrKofdSZdqk6I=,tag:+5+jXjatklsdOD4xSFB+Og==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReHZLemxJaWIvcGRlOC90
            bE9IendXcUhUaU8yY21DT0VaMmIyR0UwbkJRClhSd1V2b28yUGkzVE9zVzRvZFJV
            a2hSbjFNQllNQ2lOQ3dEaEZwdXdaUmcKLS0tIEh3NitEc3QrNjRna0Y3M0c5Ymo1
            aFlsV1E2YUl4OUtwU3Y4WDNucW5SRkUKEuTGcYcRGLd61x/l3/Tf5kYz3Vv3PBbl
            rwUTpjjm+19Lqbn7odPAckABiC/f2slwj6L32/elvqEOaXGUIBWGwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kkr0w890uzdt9dyfqdxhqajva5nlytclg4d42d37xyusql3w84ts7e0n2y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T15:46:58Z"
    mac: ENC[AES256_GCM,data:TYPQLPXHyQSMqB+orjgvcbW5nnh+uUagzg1HIVUhjBO/UtkWvTYGGGk84BNv/4M8+/3Di4MiNZygvU+jKA73z7J8lzr1Rpdvk4hm753nELbhSPNt/Fkv11X4l7bGpI4jus+Z7McZC2jxK+JJbdAyPT5XppESGVOuaLUH1CqLjv0=,iv:OlSKYuNlEPNuzcYghPyvYcLGNiJy71npQltweuKmhOA=,tag:LOQh5NZJvXuSNx8bACSpUQ==,type:str]
    version: 3.13.3
