apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yicfKtRG9CIUl2exU1yUBzrv9up1+nI6XdkanO15NA/u42Giw8xYjSuU6dD688/NjSYeBh0ttYuiCfzNW81NHoiIcU+8DVRSraAeuXDkfELsZTUHjirIpH8z2Tl4RWKmUFJQ70LFL+82lnQvtxd71hN8ciKUx5Oh7XH9M7UHtEMO6t1zqKqB8RF2CRGZaEM5CFufa3dq20wFVKowlrjxpIhhIj/n60SROHI8ZquBITVl3YIVFGXrqxR7+Wi41nnhLasbHTFPam8Iu+Do74gol7NKpelglfRA+T90sndWCPWuOtBxH7qdZgC3M7A=,iv:J1f5OqbTEDOSPUw0/darZ0W1nLEZbCp+rJxKCoE5OQg=,tag:p+7PW8tXHmOcRr6pgAwPWg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S1BLV2lSVmxqd1puVkxu
            elVHMEVOYW9RdUJDVkorNDZmdnVKbDc0YTJFCjBGQ2RtNGJxandUVDJBYlJsWjA2
            Z1hXK1BMZEgxWDRJdG1NWXhodk5BQjQKLS0tIGxMN05ibmM5T056d2FpNHpUWnFq
            M2J0Sit2MEs4bXZVTUVaWnIyMVdRTE0KPZBIBG6I4aY56y2mr453E+Pk333Mr52h
            UDuAK/WCMVvJJk6wppiTprUx8pesu0gIL/XvhfxYEF7kn2ZBAjWc/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kkr0w890uzdt9dyfqdxhqajva5nlytclg4d42d37xyusql3w84ts7e0n2y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T12:54:54Z"
    mac: ENC[AES256_GCM,data:3QASP940VZahzw/7qw++qjn5kUq7mEtqPno34LbUEipBOM8fawhRze9tS9mRa/J1YthcwMF1pm6jv4Tcmtxl139ZLYuIK9a0cekJjdipKjG76cRLBtcFRGd15blRb9ah3yW5scOQ6RDjMfuVnaJkPonIZQ6xWAdtqgpOxSzgs8o=,iv:pArz6ZU8eC5BNCEduLy0OFpOW0YGhmxgBg0N7nI0CTg=,tag:hH1mtPXRI3I7tM+SdDdx+g==,type:str]
    version: 3.13.3
