apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:RSY7O9yqDry8ldaCKdRCG0HcQSUKnkcpaLK8joXuVahrUbvGX2jrPudsnxUznnmlZ+mia3n9JaDZzi0KeK7FOiYX8ba199dWNP/6jYtnLrDdOH74EKPtTodnfJgjR2Vf9jqRmMylB9wXbPdckbpE/6eIQZVyG9xIXKjg4rYWNKB78Ch/01a4g3ullD8kBZqKx92BNmX4yxUyAp0ItyTut7YzMivnKKYvkpyF1WLbtOTDIylSNA9A+A7W3giNSWbfs/fli9AIxyPJNnJpSykAUGDvneEXCSpjt67z9rix9GD7Duqm0EZ5u+YckXs=,iv:GlbXCr/i4lnpl4AIkFLl18YXF7mq5vBVj0kzAELZpcc=,tag:l0ITqW7x4tT1RPz+8WEj0A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3clRIbTlPdG5nUjlqVHJR
            SWkxaUNrUTZwRGhaTFBtMGdmME80emFRazFjCmRSUC9PSndwMWlNQ1NNb2wzTmRL
            azRqOWVuRGZ0SlkzQU9BRzlVV3NNV0UKLS0tIGNWZmVSdG1YbGVCNDJHM201eDBo
            NmtOY2ljR2dDVjlwR2w1SWMrUThDbWMK3katZBmhyrgh1Ov83GPU1CbzWRA5sTkZ
            lC+WP839B+S2olWqGMf+vqx1HVlwxpkvK+4ve6AuosaLTwi3Rf7BvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kkr0w890uzdt9dyfqdxhqajva5nlytclg4d42d37xyusql3w84ts7e0n2y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T17:57:09Z"
    mac: ENC[AES256_GCM,data:2Jbh6L/Y6cJ0QTIyjcptiHUH4AcbDYF/DK7mpR3PiRzS/eVnEEHEsTKO3WJP7Yo9A1Z0uHLiI1pOcc24sixe6QSU3dD/yCxAhkC7Q0yc7rxpvKPaPtXGaLF+TVPvpaLa8OJW3keerhvlctdLyjVx57lyxsUCZM6Y6KOMesUBKSQ=,iv:fFmx9Mv/LnDVmtZtUUqOLPQeMeGLI0skZGHeU+0reyc=,tag:mQPGX0pNWRibFVdb4B3EvA==,type:str]
    version: 3.13.3
