apiVersion: v1
data:
    password: ENC[AES256_GCM,data:YtJ0pw==,iv:MXgF3yVIDz+lag/hjIVc8T+vWkjI6UuNSFY5MakSaaI=,tag:wQQuqU8Ad7P7R/JXh1hPbg==,type:str]
    user: ENC[AES256_GCM,data:niGYgE9gx8A=,iv:oX90GMdW1upMN0RRiUC6TEbW6QmvoMiCB9ONQyAVYLc=,tag:XBXObwRb0L7tn46Z/CdMlg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucFhlL3JlbGNhZS9uYjlj
            Y1lPRDJrZzFjWjQyMU9hRk5oQVNlcFJsK0FrClhIazZhaW9JWjl3dHVscnFvWkI0
            dEVaK2ZpeDlvTGZhRUxodi9mM3NhNG8KLS0tIFVTN1dzNWtZZ2VJMG5Nc1JESWtN
            QlJzZ25aTDZsM09udFcyT3BrL1kzRUUKpcwIA9/86I4z+6fyBcb3p822mChsyeXO
            kM1x2myiFl+KfuYH4INlZ6pyeK9+sorPBs2SKOjpWHmvmlDSscdJ6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kkr0w890uzdt9dyfqdxhqajva5nlytclg4d42d37xyusql3w84ts7e0n2y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T15:25:17Z"
    mac: ENC[AES256_GCM,data:DIxpRMlfBT4XPdK7hD5dLrIqkobm+atiiLgWty87quCBRv3yni4228cLVzHGeTiVDg9OeE4Yx8Pku6ktyItunD4qb+zIg0ycFmMVQdingzNswRo0eOF8GcMs44HbVYlbpUHe/iDtv/iD0pewtUbQpf1hHfEGZjIUDS+H/NeC8qc=,iv:87BLZFejb/TifCIAWt5Lcg6w0o00cUo6OlzvKgO7GPE=,tag:COudW/sXK39+aiUQKVqezg==,type:str]
    version: 3.13.3
